-- 1. HABILITAR COMUNICAÇÃO EXTERNA REST
EXECUTE sp_configure 'external rest endpoint enabled', 1;
RECONFIGURE WITH OVERRIDE;
GO

-- 2. CRIAÇÃO DA MASTER KEY DO BANCO
IF NOT EXISTS (SELECT * FROM sys.symmetric_keys WHERE [name] = '##MS_DatabaseMasterKey##')
    CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'MudeParaUmaSenhaForte#2026';
GO

-- 3. CREDENCIAL DO MODELO DE EMBEDDINGS (Brazil South)
CREATE DATABASE SCOPED CREDENTIAL [CHAVE_DO_MODELO]
WITH IDENTITY = 'HTTPEndpointHeaders',
     SECRET = '{"api-key":"SUA_CHAVE_AQUI"}';
GO

-- 4. CREDENCIAL DO MODELO GPT-4o (East US 2)
CREATE DATABASE SCOPED CREDENTIAL [CHAVE_DO_MODELO]
WITH IDENTITY = 'HTTPEndpointHeaders',
     SECRET = '{"api-key":"SUA_CHAVE_AQUI"}';
GO